version: "3.8"

services:
  # api-spring-webflux:
  #   build: ./
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - database
  #   environment:
  #     SPRING_R2DBC_URL: "r2dbc:pool:mysql://database:3306/spring?useSSL=false"
  #     SPRING_R2DBC_USERNAME: "root"
  #     SPRING_R2DBC_PASSWORD: "password"

  database:
    image: mysql:latest
    hostname: database
    environment:
      MYSQL_DATABASE: "spring"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
#  jenkins:
#    image: jenkins/jenkins:lts
##    privileged: true
#    user: jenkins
#    ports:
#     - "8080:8080"
#     - "50000:50000"
#    container_name: jenkins
#    volumes:
#     - jenkins:/var/jenkins_home
#     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  database:
#  jenkins:
